export const TOGGLE_VISUALIZATION = 'TOGGLE_VISUALIZATION';
export const TOGGLE_VISIBLE_COLUMN = 'TOGGLE_VISIBLE_COLUMN';
export const MULTI_SORT_ON = 'MULTI_SORT_ON';
export const MULTI_SORT_OFF = 'MULTI_SORT_OFF';
export const SELECT_ROW = 'SELECT_ROW';
export const DELETE_SELECTED_ROWS = 'DELETE_SELECTED_ROWS';
export const TOGGLE_SORTED_COLUMN = 'TOGGLE_SORTED_COLUMN';
export const SET_FILTER = 'SET_FILTER';


