export const TOGGLE_VISUALIZATION = 'TOGGLE_VISUALIZATION';
export const TOGGLE_VISIBLE_COLUMN = 'TOGGLE_VISIBLE_COLUMN';
export const SELECT_COLUMN = 'SELECT_COLUMN';
export const MULTI_SELECT_COLUMN_ON = 'MULTI_SELECT_COLUMN_ON';
export const MULTI_SELECT_COLUMN_OFF = 'MULTI_SELECT_COLUMN_OFF';
export const SELECT_ROW = 'SELECT_ROW';
export const DELETE_SELECTED_ROWS = 'DELETE_SELECTED_ROWS';
